import {
  ChangeReason,
  TickOrange,
  NameKit,
  SiteName,
  Address,
  Email,
  FirstName,
  Country,
} from "../../../HemeIconLibrary";

export const createNewSite = [
  {
    label: "Study Code",
    Icon: <NameKit />,
    type: "select",
    initialValue: "",
    placeholder: "Select study",
    required: true,
    name: "studyId",
    fluid: true,
    options: [],
  },
  {
    label: "Site Name",
    Icon: <SiteName />,
    type: "text",
    initialValue: "",
    placeholder: "Enter site name",
    required: true,
    fluid: true,
    name: "name",
  },
  {
    label: "Site Code",
    Icon: <ChangeReason />,
    type: "text",
    initialValue: "",
    placeholder: "Enter sponsor name",
    required: true,
    fluid: true,
    name: "siteCode",
  },
  {
    label: "Address",
    Icon: <Address />,
    type: "text",
    initialValue: "",
    placeholder: "Enter site address",
    required: true,
    fluid: true,
    name: "address1",
  },
  {
    label: "City",
    Icon: <Address />,
    type: "text",
    initialValue: "",
    placeholder: "Enter city",
    required: true,
    name: "city",
  },
  {
    label: "State",
    Icon: <Country />,
    type: "text",
    initialValue: "",
    placeholder: "Enter state",
    required: false,
    name: "stateProvince",
  },
  {
    label: "Country",
    Icon: <Country />,
    type: "select",
    initialValue: "",
    placeholder: "Select country",
    required: true,
    name: "countryId",
    options: [],
  },
  {
    label: "Postal Code",
    Icon: <Address />,
    type: "text",
    initialValue: "",
    placeholder: "Enter postal code",
    required: false,
    name: "postalCode",
  },

  {
    name: "isActive",
    label: "Active",
    Icon: <TickOrange />,
    type: "switch",
    initialValue: true,
    fluid: true,
    placeholder: "",
  },

  {
    label: "First Name",
    Icon: <FirstName />,
    type: "text",
    initialValue: "",
    placeholder: "Enter first name",
    required: true,
    name: "firstName",
  },
  {
    label: "Last Name",
    Icon: <FirstName />,
    type: "text",
    initialValue: "",
    placeholder: "Enter last name",
    required: true,
    name: "lastName",
  },
  {
    label: "Email",
    Icon: <Email />,
    type: "text",
    initialValue: "",
    placeholder: "Enter Email",
    required: false,
    name: "email",
  },
  {
    name: "changeReason",
    label: "Change Reason",
    Icon: <ChangeReason />,
    type: "textarea",
    fluid: true,
    initialValue: "",
    required: true,
  },
];
