import { Location, LabelDate } from '../../../HemeIconLibrary';

export const NewShippingAddress = [
  {
    label: 'Search for an address',
    Icon: <Location />,
    type: 'text',
    initialValue: '',
    placeholder: 'Search for an address',
    required: false,
    fluid: true,
    name: 'searchAddress',
  },
  {
    label: 'Street 1',
    Icon: '',
    type: 'text',
    initialValue: '',
    placeholder: 'Street 1',
    required: true,
    fluid: false,
    name: 'street1',
  },
  {
    label: 'Street 2',
    Icon: '',
    type: 'text',
    initialValue: '',
    placeholder: 'Street 2',
    required: false,
    fluid: false,
    name: 'street2',
  },
  {
    label: 'City',
    Icon: '',
    type: 'text',
    initialValue: '',
    placeholder: 'City',
    required: true,
    fluid: false,
    name: 'city',
  },
  {
    label: 'State/Region',
    Icon: '',
    type: 'text',
    initialValue: '',
    placeholder: 'State/Region',
    required: true,
    fluid: false,
    name: 'stateRegion',
  },
  {
    label: 'Postal Code',
    Icon: '',
    type: 'number',
    initialValue: '',
    placeholder: 'Postal Code',
    required: true,
    fluid: false,
    name: 'postalCode',
  },
  {
    label: 'Select a Country',
    Icon: <LabelDate />,
    type: 'select',
    initialValue: '',
    placeholder: 'Select a Country',
    required: true,
    name: 'selectCountry',
    fluid: false,
    options: [],
  },
];
