import {
  FirstName,
  Barcode,
  Request,
  Email,
  SiteName,
  LabelDate,
  LightBulb,
  Location,
} from '../../../HemeIconLibrary';

export const RequestInformation = [
  {
    heading: 'Request Details',
    fluid: true,
  },
  {
    label: 'Request Type',
    Icon: <Request />,
    type: 'text',
    initialValue: '',
    placeholder: 'Uncontrolled Request',
    required: true,
    fluid: false,
    name: 'request',
    disabled: true,
  },
  {
    label: 'Requestor Name',
    Icon: <FirstName />,
    type: 'text',
    initialValue: '',
    placeholder: 'Type name',
    required: true,
    fluid: false,
    name: 'requestorName',
  },
  {
    label: 'Requestor Email',
    Icon: <Email />,
    type: 'email',
    initialValue: '',
    placeholder: 'Type email',
    required: true,
    fluid: false,
    name: 'requestorEmail',
  },

  {
    label: 'Sponsor',
    Icon: <FirstName />,
    type: 'select',
    initialValue: '',
    placeholder: 'Type name to search and select',
    required: true,
    name: 'sponsor',
    fluid: false,
    options: [],
  },

  {
    label: 'Study #',
    Icon: <Barcode />,
    type: 'select',
    initialValue: '',
    placeholder: 'Type name to search and select',
    required: true,
    name: 'study',
    fluid: false,
    options: [],
  },
  {
    label: 'Site Code',
    Icon: <SiteName />,
    type: 'select',
    initialValue: '',
    placeholder: 'Type name to search and select',
    required: true,
    name: 'siteCode',
    fluid: false,
    options: [],
  },

  {
    label: 'Requested Date',
    Icon: <LabelDate />,
    type: 'date',
    initialValue: '',
    placeholder: 'Select a date',
    required: true,
    fluid: false,
    name: 'requestedDate',
  },
  {
    label: 'Needed By Date',
    Icon: <LabelDate />,
    type: 'date',
    initialValue: '',
    placeholder: 'Type name to search and select',
    required: true,
    fluid: false,
    name: 'neededByDate',
  },
  {
    label: 'Shipper',
    Icon: <Barcode />,
    type: 'select',
    initialValue: '',
    placeholder: 'Type name to search and select',
    required: true,
    name: 'shipper',
    fluid: false,
    options: [],
  },
  {
    heading: 'Order Details',
    fluid: true,
  },
  {
    name: 'InitialRequest',
    label: 'Initial Request',
    Icon: <Request />,
    type: 'switch',
    initialValue: false,
    placeholder: '',
    fluid: false,
  },
  {
    name: 'GreenLightRequired',
    label: 'Green Light Required',
    Icon: <LightBulb />,
    type: 'switch',
    initialValue: false,
    fluid: false,
    placeholder: '',
  },
  {
    name: 'ShipToSiteAddress',
    label: 'Ship to Site Address',
    Icon: <Location />,
    type: 'switch',
    initialValue: false,
    fluid: false,
    placeholder: '',
  },
];
